-- DDL --

CREATE TABLE STATE
(FIPS_State INT,
State_Name VARCHAR(50),
Created_Date DATETIME DEFAULT now(),
Modified_Date DATETIME DEFAULT now(),
CONSTRAINT PK_STATE PRIMARY KEY(FIPS_State));

CREATE TABLE COUNTY
(FIPS_County INT,
County_Name VARCHAR(150),
County_Category VARCHAR(50),
Census_Division INT,
Created_Date DATETIME DEFAULT now(),
Modified_Date DATETIME DEFAULT now(),
CONSTRAINT PK_COUNTY PRIMARY KEY(FIPS_County));

CREATE TABLE POPULATION
(Population_ID INT AUTO_INCREMENT,
Population INT,
Created_Date DATETIME DEFAULT now(),
Modified_Date DATETIME DEFAULT now(),
CONSTRAINT PK_POPULATION PRIMARY KEY(Population_ID));

CREATE TABLE DRUG_POISONING_MORTALITY
(Mortality_ID INT AUTO_INCREMENT,
Stat_Year INT,
Modeled_Death_Rate FLOAT,
Modeled_Standard_Deviation FLOAT,
Lower_Bound_Confidence FLOAT,
Upper_Bound_Confidence FLOAT,
FIPS_State INT,
FIPS_County INT,
Population_ID INT,
Created_Date DATETIME DEFAULT now(),
Modified_Date DATETIME DEFAULT now(),
CONSTRAINT PK_DRUG_POISONING_MORTALITY PRIMARY KEY(Mortality_ID));

ALTER TABLE DRUG_POISONING_MORTALITY
ADD CONSTRAINT FK_DRUG_POISONING_MORTALITY_FIPS_State FOREIGN KEY(FIPS_State)
REFERENCES STATE(FIPS_State);

ALTER TABLE DRUG_POISONING_MORTALITY
ADD CONSTRAINT FK_DRUG_POISONING_MORTALITY_FIPS_County FOREIGN KEY(FIPS_County)
REFERENCES COUNTY(FIPS_County);

ALTER TABLE DRUG_POISONING_MORTALITY
ADD CONSTRAINT FK_DRUG_POISONING_MORTALITY_Population_ID FOREIGN KEY(Population_ID)
REFERENCES POPULATION(Population_ID);

-- DB modifications --
ALTER TABLE DRUG_POISONING_MORTALITY
MODIFY COLUMN Modeled_Death_Rate FLOAT;

ALTER TABLE DRUG_POISONING_MORTALITY
MODIFY COLUMN Modeled_Standard_Deviation FLOAT;

ALTER TABLE DRUG_POISONING_MORTALITY
MODIFY COLUMN Lower_Bound_Confidence FLOAT;

ALTER TABLE DRUG_POISONING_MORTALITY
MODIFY COLUMN Upper_Bound_Confidence FLOAT;
